//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom13_Quan_ly_kho_hang.Model
{
    using Nhom13_Quan_ly_kho_hang.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Input : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Input()
        {
            this.InputInfoes = new HashSet<InputInfo>();
        }

        private string _Id;

        public string Id
        {
            get { return _Id; }
            set { _Id = value; OnPropertyChanged(); }
        }
        private Nullable<System.DateTime> _DateInput;

        public Nullable<System.DateTime> DateInput
        {
            get { return _DateInput; }
            set { _DateInput = value; OnPropertyChanged(); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputInfo> InputInfoes { get; set; }
    }
}
